version: "3"

services:
  mysqldbbb:
    container_name: mysqldbbb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - /home/mysql/data:/var/lib/mysql
    networks:
     - mynetworks
       
      

  
  spring_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springapp
    
    ports:
      - 9090:9090
    depends_on:
      - mysqldbbb
    networks:
      - mynetworks
       

  
networks:
  mynetworks:
   
        
