version: "3"

services:
  mysqldb:
    container_name: mysqldbb
    image: mysql:8
    restart: unless-stopped
    environment:
      MTSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - /home/mysql/data:/var/lib/mysql
    networks:
      my-network:
        ipv4_address: 172.18.0.10
      

  
  spring_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springapp
    
    ports:
      - 9090:9090
    depends_on:
      - mysqldb
    networks:
      my-network:
       

  
networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
