version: "3.9"

services:
  mysqldbbb:
    container_name: mysqldbbb
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 52000:3306
    volumes:
      - /home/mysql/data:/var/lib/mysql
    networks:
      - mynetworks

  spring_app:
    depends_on:
      - mysqldbbb
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springapp
    restart: on-failure
    ports:
      - 9090:9090
    stdin_open: true
    tty: true
    networks:
      - mynetworks

networks:
  mynetworks:
